import {
  ApiTokenDocument,
  ApiTokenQueryVariables,
  ApiTokensDocument,
  ApiTokensQueryVariables,
  BalancesDocument,
  BalancesQueryVariables,
  ChartUrlsDocument,
  ChartUrlsQueryVariables,
  FilterExchangesDocument,
  FilterExchangesQueryVariables,
  FilterNftCollectionsDocument,
  FilterNftCollectionsQueryVariables,
  FilterNftParallelAssetsDocument,
  FilterNftParallelAssetsQueryVariables,
  FilterNftPoolCollectionsDocument,
  FilterNftPoolCollectionsQueryVariables,
  FilterNftPoolsDocument,
  FilterNftPoolsQueryVariables,
  FilterPairsDocument,
  FilterPairsQueryVariables,
  FilterTokensDocument,
  FilterTokensQueryVariables,
  GetBarsDocument,
  GetBarsQueryVariables,
  GetCommunityNotesDocument,
  GetCommunityNotesQueryVariables,
  GetDetailedNftStatsDocument,
  GetDetailedNftStatsQueryVariables,
  GetDetailedPairsStatsDocument,
  GetDetailedPairsStatsQueryVariables,
  GetDetailedPairStatsDocument,
  GetDetailedPairStatsQueryVariables,
  GetDetailedStatsDocument,
  GetDetailedStatsQueryVariables,
  GetEventLabelsDocument,
  GetEventLabelsQueryVariables,
  GetExchangesDocument,
  GetExchangesQueryVariables,
  GetLatestPairsDocument,
  GetLatestPairsQueryVariables,
  GetLatestTokensDocument,
  GetLatestTokensQueryVariables,
  GetNetworksDocument,
  GetNetworksQueryVariables,
  GetNetworkStatusDocument,
  GetNetworkStatusQueryVariables,
  GetNftAssetsDocument,
  GetNftAssetsQueryVariables,
  GetNftCollectionMetadataDocument,
  GetNftCollectionMetadataQueryVariables,
  GetNftContractsDocument,
  GetNftContractsQueryVariables,
  GetNftEventsDocument,
  GetNftEventsQueryVariables,
  GetNftPoolCollectionDocument,
  GetNftPoolCollectionQueryVariables,
  GetNftPoolCollectionsByExchangeDocument,
  GetNftPoolCollectionsByExchangeQueryVariables,
  GetNftPoolDocument,
  GetNftPoolEventsDocument,
  GetNftPoolEventsQueryVariables,
  GetNftPoolQueryVariables,
  GetNftPoolsByCollectionAndExchangeDocument,
  GetNftPoolsByCollectionAndExchangeQueryVariables,
  GetNftPoolsByOwnerDocument,
  GetNftPoolsByOwnerQueryVariables,
  GetNftPoolStatsDocument,
  GetNftPoolStatsQueryVariables,
  GetParallelAssetsDocument,
  GetParallelAssetsQueryVariables,
  GetParallelCardChangesDocument,
  GetParallelCardChangesQueryVariables,
  GetPrimePoolAssetsDocument,
  GetPrimePoolAssetsQueryVariables,
  GetPrimePoolEventsDocument,
  GetPrimePoolEventsQueryVariables,
  GetPrimePoolsDocument,
  GetPrimePoolsQueryVariables,
  GetSimulateTokenContractResultsDocument,
  GetSimulateTokenContractResultsQueryVariables,
  GetSymbolDocument,
  GetSymbolQueryVariables,
  GetTokenCountDocument,
  GetTokenCountQueryVariables,
  GetTokenEventsDocument,
  GetTokenEventsQueryVariables,
  GetTokenInfoDocument,
  GetTokenInfoQueryVariables,
  GetTokenPricesDocument,
  GetTokenPricesQueryVariables,
  GetTokensInfoDocument,
  GetTokensInfoQueryVariables,
  GetUniV3TicksDocument,
  GetUniV3TicksQueryVariables,
  GetWebhooksDocument,
  GetWebhooksQueryVariables,
  HoldersDocument,
  HoldersQueryVariables,
  LiquidityLocksDocument,
  LiquidityLocksQueryVariables,
  LiquidityMetadataDocument,
  LiquidityMetadataQueryVariables,
  ListFavoriteTokensDocument,
  ListFavoriteTokensQueryVariables,
  ListPairsForTokenDocument,
  ListPairsForTokenQueryVariables,
  ListPairsWithMetadataForTokenDocument,
  ListPairsWithMetadataForTokenQueryVariables,
  ListTopTokensDocument,
  ListTopTokensQueryVariables,
  NftHoldersDocument,
  NftHoldersQueryVariables,
  PairMetadataDocument,
  PairMetadataQueryVariables,
  PrimeBalanceDocument,
  PrimeBalanceQueryVariables,
  PrimeHoldersDocument,
  PrimeHoldersQueryVariables,
  SearchNftsDocument,
  SearchNftsQueryVariables,
  SearchTokensDocument,
  SearchTokensQueryVariables,
  TokenDocument,
  TokenLifecycleEventsDocument,
  TokenLifecycleEventsQueryVariables,
  TokenQueryVariables,
  TokensDocument,
  TokenSparklinesDocument,
  TokenSparklinesQueryVariables,
  TokensQueryVariables,
  WalletNftCollectionAssetsDocument,
  WalletNftCollectionAssetsQueryVariables,
  WalletNftCollectionsDocument,
  WalletNftCollectionsQueryVariables,
} from "./autogenerated/graphql";
import { Codex } from "./index";

export class Query {
  constructor(private sdk: Codex) {}
  apiToken = async (vars: ApiTokenQueryVariables) =>
    this.sdk.query(ApiTokenDocument, vars);
  apiTokens = async (vars: ApiTokensQueryVariables) =>
    this.sdk.query(ApiTokensDocument, vars);
  balances = async (vars: BalancesQueryVariables) =>
    this.sdk.query(BalancesDocument, vars);
  chartUrls = async (vars: ChartUrlsQueryVariables) =>
    this.sdk.query(ChartUrlsDocument, vars);
  filterExchanges = async (vars: FilterExchangesQueryVariables) =>
    this.sdk.query(FilterExchangesDocument, vars);
  filterNftCollections = async (vars: FilterNftCollectionsQueryVariables) =>
    this.sdk.query(FilterNftCollectionsDocument, vars);
  filterNftParallelAssets = async (
    vars: FilterNftParallelAssetsQueryVariables,
  ) => this.sdk.query(FilterNftParallelAssetsDocument, vars);
  filterNftPoolCollections = async (
    vars: FilterNftPoolCollectionsQueryVariables,
  ) => this.sdk.query(FilterNftPoolCollectionsDocument, vars);
  filterNftPools = async (vars: FilterNftPoolsQueryVariables) =>
    this.sdk.query(FilterNftPoolsDocument, vars);
  filterPairs = async (vars: FilterPairsQueryVariables) =>
    this.sdk.query(FilterPairsDocument, vars);
  filterTokens = async (vars: FilterTokensQueryVariables) =>
    this.sdk.query(FilterTokensDocument, vars);
  getBars = async (vars: GetBarsQueryVariables) =>
    this.sdk.query(GetBarsDocument, vars);
  getCommunityNotes = async (vars: GetCommunityNotesQueryVariables) =>
    this.sdk.query(GetCommunityNotesDocument, vars);
  getDetailedNftStats = async (vars: GetDetailedNftStatsQueryVariables) =>
    this.sdk.query(GetDetailedNftStatsDocument, vars);
  getDetailedPairStats = async (vars: GetDetailedPairStatsQueryVariables) =>
    this.sdk.query(GetDetailedPairStatsDocument, vars);
  getDetailedPairsStats = async (vars: GetDetailedPairsStatsQueryVariables) =>
    this.sdk.query(GetDetailedPairsStatsDocument, vars);
  getDetailedStats = async (vars: GetDetailedStatsQueryVariables) =>
    this.sdk.query(GetDetailedStatsDocument, vars);
  getEventLabels = async (vars: GetEventLabelsQueryVariables) =>
    this.sdk.query(GetEventLabelsDocument, vars);
  getExchanges = async (vars: GetExchangesQueryVariables) =>
    this.sdk.query(GetExchangesDocument, vars);
  getLatestPairs = async (vars: GetLatestPairsQueryVariables) =>
    this.sdk.query(GetLatestPairsDocument, vars);
  getLatestTokens = async (vars: GetLatestTokensQueryVariables) =>
    this.sdk.query(GetLatestTokensDocument, vars);
  getNetworkStatus = async (vars: GetNetworkStatusQueryVariables) =>
    this.sdk.query(GetNetworkStatusDocument, vars);
  getNetworks = async (vars: GetNetworksQueryVariables) =>
    this.sdk.query(GetNetworksDocument, vars);
  getNftAssets = async (vars: GetNftAssetsQueryVariables) =>
    this.sdk.query(GetNftAssetsDocument, vars);
  getNftCollectionMetadata = async (
    vars: GetNftCollectionMetadataQueryVariables,
  ) => this.sdk.query(GetNftCollectionMetadataDocument, vars);
  getNftContracts = async (vars: GetNftContractsQueryVariables) =>
    this.sdk.query(GetNftContractsDocument, vars);
  getNftEvents = async (vars: GetNftEventsQueryVariables) =>
    this.sdk.query(GetNftEventsDocument, vars);
  getNftPool = async (vars: GetNftPoolQueryVariables) =>
    this.sdk.query(GetNftPoolDocument, vars);
  getNftPoolCollection = async (vars: GetNftPoolCollectionQueryVariables) =>
    this.sdk.query(GetNftPoolCollectionDocument, vars);
  getNftPoolCollectionsByExchange = async (
    vars: GetNftPoolCollectionsByExchangeQueryVariables,
  ) => this.sdk.query(GetNftPoolCollectionsByExchangeDocument, vars);
  getNftPoolEvents = async (vars: GetNftPoolEventsQueryVariables) =>
    this.sdk.query(GetNftPoolEventsDocument, vars);
  getNftPoolStats = async (vars: GetNftPoolStatsQueryVariables) =>
    this.sdk.query(GetNftPoolStatsDocument, vars);
  getNftPoolsByCollectionAndExchange = async (
    vars: GetNftPoolsByCollectionAndExchangeQueryVariables,
  ) => this.sdk.query(GetNftPoolsByCollectionAndExchangeDocument, vars);
  getNftPoolsByOwner = async (vars: GetNftPoolsByOwnerQueryVariables) =>
    this.sdk.query(GetNftPoolsByOwnerDocument, vars);
  getParallelAssets = async (vars: GetParallelAssetsQueryVariables) =>
    this.sdk.query(GetParallelAssetsDocument, vars);
  getParallelCardChanges = async (vars: GetParallelCardChangesQueryVariables) =>
    this.sdk.query(GetParallelCardChangesDocument, vars);
  getPrimePoolAssets = async (vars: GetPrimePoolAssetsQueryVariables) =>
    this.sdk.query(GetPrimePoolAssetsDocument, vars);
  getPrimePoolEvents = async (vars: GetPrimePoolEventsQueryVariables) =>
    this.sdk.query(GetPrimePoolEventsDocument, vars);
  getPrimePools = async (vars: GetPrimePoolsQueryVariables) =>
    this.sdk.query(GetPrimePoolsDocument, vars);
  getSimulateTokenContractResults = async (
    vars: GetSimulateTokenContractResultsQueryVariables,
  ) => this.sdk.query(GetSimulateTokenContractResultsDocument, vars);
  getSymbol = async (vars: GetSymbolQueryVariables) =>
    this.sdk.query(GetSymbolDocument, vars);
  getTokenCount = async (vars: GetTokenCountQueryVariables) =>
    this.sdk.query(GetTokenCountDocument, vars);
  getTokenEvents = async (vars: GetTokenEventsQueryVariables) =>
    this.sdk.query(GetTokenEventsDocument, vars);
  getTokenInfo = async (vars: GetTokenInfoQueryVariables) =>
    this.sdk.query(GetTokenInfoDocument, vars);
  getTokenPrices = async (vars: GetTokenPricesQueryVariables) =>
    this.sdk.query(GetTokenPricesDocument, vars);
  getTokensInfo = async (vars: GetTokensInfoQueryVariables) =>
    this.sdk.query(GetTokensInfoDocument, vars);
  getUniV3Ticks = async (vars: GetUniV3TicksQueryVariables) =>
    this.sdk.query(GetUniV3TicksDocument, vars);
  getWebhooks = async (vars: GetWebhooksQueryVariables) =>
    this.sdk.query(GetWebhooksDocument, vars);
  holders = async (vars: HoldersQueryVariables) =>
    this.sdk.query(HoldersDocument, vars);
  liquidityLocks = async (vars: LiquidityLocksQueryVariables) =>
    this.sdk.query(LiquidityLocksDocument, vars);
  liquidityMetadata = async (vars: LiquidityMetadataQueryVariables) =>
    this.sdk.query(LiquidityMetadataDocument, vars);
  listFavoriteTokens = async (vars: ListFavoriteTokensQueryVariables) =>
    this.sdk.query(ListFavoriteTokensDocument, vars);
  listPairsForToken = async (vars: ListPairsForTokenQueryVariables) =>
    this.sdk.query(ListPairsForTokenDocument, vars);
  listPairsWithMetadataForToken = async (
    vars: ListPairsWithMetadataForTokenQueryVariables,
  ) => this.sdk.query(ListPairsWithMetadataForTokenDocument, vars);
  listTopTokens = async (vars: ListTopTokensQueryVariables) =>
    this.sdk.query(ListTopTokensDocument, vars);
  nftHolders = async (vars: NftHoldersQueryVariables) =>
    this.sdk.query(NftHoldersDocument, vars);
  pairMetadata = async (vars: PairMetadataQueryVariables) =>
    this.sdk.query(PairMetadataDocument, vars);
  primeBalance = async (vars: PrimeBalanceQueryVariables) =>
    this.sdk.query(PrimeBalanceDocument, vars);
  primeHolders = async (vars: PrimeHoldersQueryVariables) =>
    this.sdk.query(PrimeHoldersDocument, vars);
  searchNfts = async (vars: SearchNftsQueryVariables) =>
    this.sdk.query(SearchNftsDocument, vars);
  searchTokens = async (vars: SearchTokensQueryVariables) =>
    this.sdk.query(SearchTokensDocument, vars);
  token = async (vars: TokenQueryVariables) =>
    this.sdk.query(TokenDocument, vars);
  tokenLifecycleEvents = async (vars: TokenLifecycleEventsQueryVariables) =>
    this.sdk.query(TokenLifecycleEventsDocument, vars);
  tokenSparklines = async (vars: TokenSparklinesQueryVariables) =>
    this.sdk.query(TokenSparklinesDocument, vars);
  tokens = async (vars: TokensQueryVariables) =>
    this.sdk.query(TokensDocument, vars);
  walletNftCollectionAssets = async (
    vars: WalletNftCollectionAssetsQueryVariables,
  ) => this.sdk.query(WalletNftCollectionAssetsDocument, vars);
  walletNftCollections = async (vars: WalletNftCollectionsQueryVariables) =>
    this.sdk.query(WalletNftCollectionsDocument, vars);
}
